version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_USER: jobvacancy
      POSTGRES_DB: jobvacancy
    ports:
      - "5432:5432"
